version: 0.2
phases:
  install:
    commands:
      - yarn config set cache-folder /root/.yarn-cache
      - yarn install --production --frozen-lockfile
  build:
    commands:
      - echo Build started on `date`
      - yarn build:env
  post_build:
    commands:
      - aws s3 cp build s3://$WEB_S3_BUCKET_NAME --recursive
      - aws cloudfront create-invalidation --distribution-id $WEB_CLOUDFRONT_DIST_ID --paths /\*
artifacts:
  base-directory: "build"
  files:
    - "**/*"
cache:
  paths:
    - "/root/.yarn-cache/**/*"
    - "node_modules/**/*"